version: '2'

services:
  godot:
    build: .
    ports:
      - "5555:5555"
      - "5900:5900"
    tty: true
    volumes:
      - ./context:/context
    container_name: gamebuildr/godot-universal:2.1.5
